TEXT_GAMEOVER = "GAME OVER";
TEXT_SCORE = "TOTAL SCORE";
TEXT_HELP1_PC = "PRESS SCREEN TO SWITCH";
TEXT_HELP1_MOBILE = "TOUCH DISPLAY TO SWITCH";
TEXT_POWER = "POWER";
TEXT_EFFECT = "EFFECT";
TEXT_TOTAL = "TOTAL";
TEXT_ARE_SURE = "ARE YOU SURE?";
TEXT_CREDITS_DEVELOPED = "...";
TEXT_LINK1 = "2017";
TEXT_MOVE = "MOVE";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better?";